In [1]:
import pandas as pd

In [2]:
data = pd.read_csv(r"C:\Users\XBOX2\Desktop\hackthons\hackthon\data\archive(1)\studentInfo.csv")

In [3]:
student_info = pd.DataFrame(data)

In [4]:
student_info.head()

,code_module,code_presentation,id_student,gender,region,highest_education,imd_band,age_band,num_of_prev_attempts,studied_credits,disability,final_result
0,AAA,2013J,11391,M,East Anglian Region,HE Qualification,90-100%,55<=,0,240,N,Pass
1,AAA,2013J,28400,F,Scotland,HE Qualification,20-30%,35-55,0,60,N,Pass
2,AAA,2013J,30268,F,North Western Region,A Level or Equivalent,30-40%,35-55,0,60,Y,Withdrawn
3,AAA,2013J,31604,F,South East Region,A Level or Equivalent,50-60%,35-55,0,60,N,Pass
4,AAA,2013J,32885,F,West Midlands Region,Lower Than A Level,50-60%,0-35,0,60,N,Pass

In [5]:
student_info['region'].unique()

array(['East Anglian Region', 'Scotland', 'North Western Region',
       'South East Region', 'West Midlands Region', 'Wales',
       'North Region', 'South Region', 'Ireland', 'South West Region',
       'East Midlands Region', 'Yorkshire Region', 'London Region'],
      dtype=object)

In [6]:
student_info['imd_band'].unique()

array(['90-100%', '20-30%', '30-40%', '50-60%', '80-90%', '70-80%', nan,
       '60-70%', '40-50%', '10-20', '0-10%'], dtype=object)

In [10]:
(student_info['imd_band'].isna().sum() / student_info.shape[0])*100

np.float64(3.408707391157611)

In [11]:
student_info.shape

(32593, 12)

In [14]:
student_info[student_info['region'] == 'East Anglian Region']

,code_module,code_presentation,id_student,gender,region,highest_education,imd_band,age_band,num_of_prev_attempts,studied_credits,disability,final_result
0,AAA,2013J,11391,M,East Anglian Region,HE Qualification,90-100%,55<=,0,240,N,Pass
8,AAA,2013J,52130,F,East Anglian Region,A Level or Equivalent,70-80%,0-35,0,90,N,Pass
11,AAA,2013J,58873,F,East Anglian Region,A Level or Equivalent,20-30%,0-35,0,60,N,Pass
12,AAA,2013J,59185,M,East Anglian Region,Lower Than A Level,60-70%,35-55,0,60,N,Pass
15,AAA,2013J,65002,F,East Anglian Region,A Level or Equivalent,70-80%,0-35,0,60,N,Withdrawn
...,...,...,...,...,...,...,...,...,...,...,...,...
32539,GGG,2014J,697325,F,East Anglian Region,Lower Than A Level,90-100%,0-35,0,30,Y,Distinction
32557,GGG,2014J,1827650,F,East Anglian Region,A Level or Equivalent,20-30%,0-35,0,30,N,Distinction
32565,GGG,2014J,2004143,F,East Anglian Region,Lower Than A Level,50-60%,0-35,0,30,N,Pass
32582,GGG,2014J,2475886,F,East Anglian Region,Lower Than A Level,40-50%,35-55,0,90,N,Fail
32589,GGG,2014J,2645731,F,East Anglian Region,Lower Than A Level,40-50%,35-55,0,30,N,Distinction

In [15]:
student_info.isna().sum()

code_module                0
code_presentation          0
id_student                 0
gender                     0
region                     0
highest_education          0
imd_band                1111
age_band                   0
num_of_prev_attempts       0
studied_credits            0
disability                 0
final_result               0
dtype: int64

In [17]:
from sklearn.impute import SimpleImputer
import numpy as np

In [20]:
imp_mode = SimpleImputer(missing_values=np.nan , strategy= 'most_frequent')

In [21]:
student_info_cleaned = imp_mode.fit_transform(student_info)

In [23]:
student_info_cleaned = pd.DataFrame(student_info_cleaned, columns= student_info.columns)

In [32]:
student_info_cleaned.sample(10)

,code_module,code_presentation,id_student,gender,region,highest_education,imd_band,age_band,num_of_prev_attempts,studied_credits,disability,final_result
16178,DDD,2013J,2175266,M,Wales,HE Qualification,50-60%,35-55,0,60,N,Withdrawn
32108,GGG,2014J,644252,F,East Anglian Region,Lower Than A Level,30-40%,0-35,0,30,N,Fail
11898,CCC,2014J,620819,M,Ireland,A Level or Equivalent,60-70%,0-35,0,90,N,Withdrawn
2695,BBB,2013J,287309,F,South West Region,Lower Than A Level,40-50%,0-35,2,120,N,Pass
13898,DDD,2013B,544296,F,London Region,A Level or Equivalent,0-10%,0-35,0,90,N,Withdrawn
22517,FFF,2013B,334224,M,North Western Region,Lower Than A Level,0-10%,0-35,0,60,Y,Fail
24803,FFF,2013J,569016,M,West Midlands Region,Lower Than A Level,0-10%,35-55,0,60,N,Pass
26620,FFF,2014B,550498,M,Yorkshire Region,Lower Than A Level,50-60%,0-35,0,60,N,Fail
4102,BBB,2013J,596583,F,Scotland,A Level or Equivalent,60-70%,35-55,0,60,N,Fail
12451,CCC,2014J,675374,M,South Region,HE Qualification,70-80%,35-55,0,60,N,Pass

In [27]:
student_info_cleaned.isna().sum()

code_module             0
code_presentation       0
id_student              0
gender                  0
region                  0
highest_education       0
imd_band                0
age_band                0
num_of_prev_attempts    0
studied_credits         0
disability              0
final_result            0
dtype: int64

In [29]:
student_info_cleaned.duplicated().sum()

np.int64(0)

In [30]:
from sklearn.preprocessing import OneHotEncoder

In [33]:
from scipy.stats import chi2_contingency

In [34]:
table = pd.crosstab(student_info_cleaned['highest_education'],student_info_cleaned['final_result'])
chi2 , p,dof, expected = chi2_contingency(table)

In [ ]:
table2 = pd.crosstab(student_info_cleaned['imd_band'])

In [35]:
print("p-value",p)

p-value 9.18211300726649e-212

In [36]:
dof

12

In [37]:
expected

array([[1303.10434756, 3038.85312797, 5326.61138895, 4376.43113552],
       [ 438.85251434, 1023.40870739, 1793.86770165, 1473.87107661],
       [1220.80790354, 2846.93694965, 4990.21378824, 4100.04135857],
       [  32.19488847,   75.07882061,  131.60086522,  108.1254257 ],
       [  29.04034609,   67.72239438,  118.70625594,   97.53100359]])

In [38]:
table

final_result                 Distinction  Fail  Pass  Withdrawn
highest_education
A Level or Equivalent               1496  2707  5812       4030
HE Qualification                     697   790  1960       1283
Lower Than A Level                   727  3426  4385       4620
No Formal quals                       16    95    87        149
Post Graduate Qualification           88    34   117         74

In [40]:
student_info_cleaned['final_result'].value_counts(normalize= True)

final_result
Pass           0.379253
Withdrawn      0.311601
Fail           0.216365
Distinction    0.092781
Name: proportion, dtype: float64