In [3]:
import pandas as pd
from pathlib import Path
withdrawal_students = pd.read_csv("data/final_vle.csv")
withdrawal_students = withdrawal_students[withdrawal_students["final_result"] == "Withdrawn"]
withdrawal_students

,index,code_module,code_presentation,id_student,gender,region,highest_education,imd_band,age_band,num_of_prev_attempts,studied_credits,disability,final_result,date_registration,date_unregistration,avg_score,max_score,num_submissions,total_clicks,activity_diversity
2,2,AAA,2013J,30268,F,North Western Region,A Level or Equivalent,30-40%,35-55,0,60,Y,Withdrawn,-92.0,12.0,NaN,NaN,NaN,281.0,6.0
15,15,AAA,2013J,65002,F,East Anglian Region,A Level or Equivalent,70-80%,0-35,0,60,N,Withdrawn,-180.0,96.0,67.0,68.0,2.0,171.0,6.0
22,22,AAA,2013J,94961,M,South Region,Lower Than A Level,70-80%,35-55,0,60,N,Withdrawn,-170.0,72.0,74.0,74.0,1.0,339.0,6.0
29,29,AAA,2013J,106247,M,South Region,HE Qualification,80-90%,35-55,0,60,N,Withdrawn,5.0,175.0,60.0,67.0,3.0,465.0,7.0
41,41,AAA,2013J,129955,M,West Midlands Region,A Level or Equivalent,50-60%,0-35,0,60,N,Withdrawn,-197.0,135.0,81.0,85.0,3.0,1011.0,8.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32576,32576,GGG,2014J,2338614,F,Scotland,A Level or Equivalent,0-10%,35-55,0,30,Y,Withdrawn,-23.0,58.0,NaN,NaN,NaN,51.0,5.0
32577,32577,GGG,2014J,2342238,M,Ireland,HE Qualification,80-90%,0-35,0,30,N,Withdrawn,-45.0,74.0,50.0,50.0,1.0,118.0,4.0
32578,32578,GGG,2014J,2357806,F,Ireland,Lower Than A Level,40-50%,35-55,0,30,N,Withdrawn,-128.0,73.0,76.5,80.0,2.0,58.0,4.0
32586,32586,GGG,2014J,2608143,M,East Midlands Region,HE Qualification,60-70%,35-55,0,30,N,Withdrawn,-45.0,48.0,NaN,NaN,NaN,37.0,5.0
32591,32591,GGG,2014J,2679821,F,South East Region,Lower Than A Level,90-100%,35-55,0,30,N,Withdrawn,-49.0,101.0,91.5,100.0,2.0,275.0,6.0

In [4]:
withdrawal_students.dropna()

,index,code_module,code_presentation,id_student,gender,region,highest_education,imd_band,age_band,num_of_prev_attempts,studied_credits,disability,final_result,date_registration,date_unregistration,avg_score,max_score,num_submissions,total_clicks,activity_diversity
15,15,AAA,2013J,65002,F,East Anglian Region,A Level or Equivalent,70-80%,0-35,0,60,N,Withdrawn,-180.0,96.0,67.000000,68.0,2.0,171.0,6.0
22,22,AAA,2013J,94961,M,South Region,Lower Than A Level,70-80%,35-55,0,60,N,Withdrawn,-170.0,72.0,74.000000,74.0,1.0,339.0,6.0
29,29,AAA,2013J,106247,M,South Region,HE Qualification,80-90%,35-55,0,60,N,Withdrawn,5.0,175.0,60.000000,67.0,3.0,465.0,7.0
41,41,AAA,2013J,129955,M,West Midlands Region,A Level or Equivalent,50-60%,0-35,0,60,N,Withdrawn,-197.0,135.0,81.000000,85.0,3.0,1011.0,8.0
45,45,AAA,2013J,135400,F,South East Region,Lower Than A Level,90-100%,35-55,0,60,Y,Withdrawn,-32.0,144.0,61.500000,72.0,2.0,287.0,6.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32568,32568,GGG,2014J,2203216,F,Wales,A Level or Equivalent,80-90%,35-55,0,30,N,Withdrawn,-9.0,125.0,55.000000,55.0,1.0,232.0,5.0
32569,32569,GGG,2014J,2214722,F,Scotland,A Level or Equivalent,70-80%,35-55,0,30,N,Withdrawn,-23.0,206.0,92.166667,100.0,6.0,410.0,5.0
32577,32577,GGG,2014J,2342238,M,Ireland,HE Qualification,80-90%,0-35,0,30,N,Withdrawn,-45.0,74.0,50.000000,50.0,1.0,118.0,4.0
32578,32578,GGG,2014J,2357806,F,Ireland,Lower Than A Level,40-50%,35-55,0,30,N,Withdrawn,-128.0,73.0,76.500000,80.0,2.0,58.0,4.0
32591,32591,GGG,2014J,2679821,F,South East Region,Lower Than A Level,90-100%,35-55,0,30,N,Withdrawn,-49.0,101.0,91.500000,100.0,2.0,275.0,6.0